#!/usr/bin/env python
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0

"""Regenerate the overlay figure's row-2 topic tables (emb_cluster_topics.tex).

Three side-by-side minipages, one per embedding, listing the 10 shown clusters.
Each row is a Vivid cluster swatch + C-id (linking to the overlay map) and the
LLM topic phrase with words colour-coded by category (appearance/activity/
objects), reusing the lexicon from ``topic_lexicon``. Each table is
wrapped in ``\\resizebox`` so every theme stays on one line.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.colors as mcolors
import pandas as pd

from cluster_select import distinct_clusters as _distinct_clusters
from topic_lexicon import APPEAR, ACTIVITY, NEUTRAL, OBJECT
from topic_lexicon import categorize as _color
from topic_lexicon import latex_escape as _esc

_FOCUS = {APPEAR: ("appearance", "2166AC"), ACTIVITY: ("activity", "C2451E"),
          OBJECT: ("objects", "1B7837")}

_PAL = ["#E58606", "#5D69B1", "#52BCA3", "#99C945", "#CC61B0", "#24796C",
        "#DAA51B", "#2F8AC4", "#764E9F", "#ED645A", "#CC3A8E", "#A5AA99"]


def _theme(td):
    return td.get("description") or ", ".join(td.get("keywords", [])[:5])


def _texword(w):
    c = _color(w)
    return _esc(w) if c == NEUTRAL else \
        r"\textcolor[HTML]{%s}{\textbf{%s}}" % (c.lstrip("#").upper(), _esc(w))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--clustering-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--k", type=int, default=10)
    args = ap.parse_args(argv)

    cols = [("k50_cosmos", "Cosmos-Embed1"), ("k50_caption", "Caption (Qwen3-Embedding-8B)"),
            ("k50_visual", "Visual (Florence-2/SigLIP)")]
    percol = []
    for rid, name in cols:
        run = args.clustering_dir / rid
        topics = json.loads((run / "cluster_topics.json").read_text())["topics"]
        df = pd.read_parquet(run / "cluster_assignments.parquet", columns=["clip_id", "cluster_id"])
        sizes = df.groupby("cluster_id").size()
        clusters = _distinct_clusters(run, sizes, args.k, 0.5)
        cells = []
        for i, c in enumerate(clusters):
            r, g, b = mcolors.to_rgb(_PAL[i % len(_PAL)])
            sw = r"\textcolor[rgb]{%.3f,%.3f,%.3f}{\rule{1.1ex}{1.1ex}}" % (r, g, b)
            th = _theme(topics[str(c)])
            cells.append(r"%s~\textbf{C%d}~%s" % (sw, c, " ".join(_texword(w) for w in th.split())))
        percol.append(cells)
    n = max(len(c) for c in percol)
    # ONE tabular in a SINGLE \resizebox: uniform font across the three columns,
    # l columns + no wrapping keep every topic on one line.
    out = ["% Colour-coded cluster-topic tables (row 2 of fig:emb_cluster_scenarios).",
           "% Generated by make_overlay_topics_table.py; \\input from 4_experiments.tex.",
           r"\resizebox{\linewidth}{!}{%",
           r"\begin{tabular}{@{}l@{\hskip 1.6em}l@{\hskip 1.6em}l@{}}",
           " & ".join(r"\textbf{%s}" % name for _, name in cols) + r" \\[4pt]"]
    for i in range(n):
        out.append(" & ".join(percol[j][i] if i < len(percol[j]) else "" for j in range(3)) + r" \\")
    out += [r"\end{tabular}}"]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n")
    print("wrote", args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
