#!/usr/bin/env python
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0

"""Hierarchical comparison table: three embeddings side by side, each showing a
few level-1 branches refining into level-2 sub-clusters.

Same style as the overlay table: a per-column colour-coded focus tag (from the
embedding's topic-word category shares) plus category-coloured keywords. Shows
(1) recursion produces finer labels layer by layer and (2) each embedding refines
along its own focus direction. \\input from 4_experiments.tex.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from make_taxonomy_compare import APPEAR, ACTIVITY, OBJECT, NEUTRAL, _color, _esc

_FOCUS = {APPEAR: ("appearance", "2166AC"), ACTIVITY: ("activity", "C2451E"),
          OBJECT: ("objects", "1B7837")}


def _phrase(v, n=3):
    return v.get("description") or ", ".join(v.get("keywords", [])[:n])


def _cw(w):
    c = _color(w)
    return _esc(w) if c == NEUTRAL else \
        r"\textcolor[HTML]{%s}{\textbf{%s}}" % (c.lstrip("#").upper(), _esc(w))


def _cphrase(s):
    return " ".join(_cw(w) for w in s.split())


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--hier-base", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--branches", type=int, default=3, help="level-1 branches shown per embedding")
    ap.add_argument("--children", type=int, default=3, help="level-2 sub-clusters per branch")
    args = ap.parse_args(argv)

    cols = [("pai_cosmos", "Cosmos-Embed1"), ("pai_caption", "Caption (Qwen3-Embedding-8B)"),
            ("pai_visual", "Visual (Florence-2/SigLIP)")]
    out = ["% Hierarchical level-1 -> level-2 comparison (fig:emb_cluster_taxonomy).",
           "% Generated by make_hier_compare.py; \\input from 4_experiments.tex."]
    for j, (d, name) in enumerate(cols):
        t = json.loads((args.hier_base / d / "hier_topics.json").read_text())
        l1 = sorted((p for p, v in t.items() if v["depth"] == 1), key=lambda p: -t[p]["size"])
        out.append(r"\begin{minipage}[t]{0.32\linewidth}")
        out.append(r"{\footnotesize\textbf{%s}}\\[3pt]" % name)
        out.append(r"{\scriptsize\begin{tabular}{@{}p{0.96\linewidth}@{}}")
        for p in l1[:args.branches]:
            out.append(r"\textbf{C%s}~%s \\" % (p, _cphrase(_phrase(t[p]))))
            kids = sorted((q for q in t if q.startswith(p + ".") and t[q]["depth"] == 2),
                          key=lambda q: -t[q]["size"])[:args.children]
            for q in kids:
                out.append(r"\hspace{1.1em}\textendash\ %s \\" % _cphrase(_phrase(t[q], 2)))
            out.append(r"\addlinespace[2pt]")
        out.append(r"\end{tabular}}")
        out.append(r"\end{minipage}" + (r"\hfill" if j < len(cols) - 1 else ""))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out) + "\n")
    print("wrote", args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
